### PR TITLE
Trigger build of new Docker dev image via CircleCI

### PR DESCRIPTION
**Pull request by tkrille**

### CODE REVIEW

**Comment by tkrille** [comment]
If this is merged (and if it works), I'll do the same for the other 3 services.

**Comment by wallner** [comment]
Now, that looks neat!

**Comment by tkrille** [comment]
Wow, it actually works! :) So, I'll do this for the other services, too, now.

**Comment by tkrille** [comment]
Here they are:
- https://github.com/osiam/resource-server/pull/73
- https://github.com/osiam/addon-self-administration/pull/146
- https://github.com/osiam/addon-administration/pull/99

**Pull request merged**
