### PR TITLE
Remove scopes key from access token

### PR DESCRIPTION
**Pull request by dacrome**
Closes [#51](https://github.com/osiam/auth-server/issues/51)

### CODE REVIEW

**Comment by dacrome** [comment]
These will break the API so a major version bump is necessary!

**Comment by wallner** [comment]
Please add an entry to the file  `CHANGELOG.md` in case anybody uses it even though it's not in the documented API

**Comment by wallner** [comment]
Thank you!

**Comment by dacrome** [comment]
Actually this is not a breaking change, because OSIAMs [access token](https://github.com/osiam/connector4java/blob/1c718ff1a5ea79a2e3814ebc7a372c81b5f6d243/src/main/java/org/osiam/client/oauth/AccessToken.java#L52) hasn't an attribute called `scopes`.

**Pull request merged**
