### PR TITLE
Extend configuration by parameters for pools and timeouts

### LINKED ISSUE #81: Properties for Connection-Pool
We need properties for the connection pool (how many connection and the connection timeout) of the internal connector4java. And we need also a property for the DB-Pool-Size (hikari).

### PR DESCRIPTION
**Pull request by tkrille**
This is part of the efforts to support more parallel requests. See also #81.

Resolves #81

### CODE REVIEW

**Comment by tkrille** [comment]
@sschum @dzeihs Can you take a look at this?

**Comment by wallner** [comment]
Looks good to me. If @sschum @dzeihs agree, I'm happy to merge it

**Comment by sschum** [comment]
It looks good for us.

**Comment by tkrille** [comment]
Then, please, merge it.

**Pull request merged**
